version: "3.7"
 
services:
  api-node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: back
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    command: npm run dev